Feature/2216 grafana endpoint to see how many ecr repos are out of sync
dfds/selfservice-api pull request #141
Opened 2024-01-10 14:25 UTC by paulseghers

closes dfds/cloudplatform/issues/2216

# Additional Review Notes
Because of low knowledge I ended up going down the "wrong" path for 70% of this PR, however I'm still leaving the code for this.
Essentially we are exposing the metrics in two ways:
- a `Prometheus.Metrics.Gauge` which comes with its own prometheus .net functions to update it
- an in-memory global variable which gets exposed on a conventional http endpoint 
Only the first one is actually needed, but I've made a background service which updates both ¯\_(ツ)_/¯

2024-01-11 08:51 UTC, kralle333 requested changes
mostly good, but I have some comments

2024-01-11 08:51 UTC, kralle333 commented on src/SelfService/Infrastructure/Api/Metrics/MetricsController.cs
> +    }
copy paste mistakes

2024-01-11 08:51 UTC, kralle333 commented on src/SelfService/Infrastructure/BackgroundJobs/UpdateOutOfSyncECRRepos.cs
> +                    await Task.Delay(TimeSpan.FromMinutes(1), stoppingToken); //maybe each minute is a lot?
I would make it lazy instead. Just update on need if its older than some amount of time (12 hours?)

2024-01-11 08:58 UTC, paulseghers commented on src/SelfService/Infrastructure/Api/Metrics/MetricsController.cs
> +    }
thx

2024-01-15 12:18 UTC, kralle333 approved these changes
good

2024-01-15 12:19 UTC, merged