working cloud engineer permissions
dfds/selfservice-api pull request #182
Opened 2024-06-24 12:29 UTC by HrisyToteva

closes dfds/cloudplatform/issues/2832

# Additional Review Notes
Functionality to disable the cloud engineer role permissions

2024-06-24 13:45 UTC, andreasfrisch requested changes
I am really glad that we finally have this, but I think we should do things a slightly different way 👍 
Let's talk about this :)

2024-06-24 13:45 UTC, andreasfrisch commented on src/SelfService/Domain/Services/AuthorizationService.cs
> +        Console.WriteLine();
Is this needed anymore?

2024-06-24 13:45 UTC, andreasfrisch commented on src/SelfService/Domain/Services/AuthorizationService.cs
> +        if (portalUser.Roles.Any(role => role == UserRole.CloudEngineer))
We have this particular code in multiple parts; Should we extract it and thus simplify these sections? :)

2024-06-24 13:45 UTC, andreasfrisch commented on src/SelfService/Infrastructure/Api/UserImpersonation.cs
> +                context.Items["userPermissions"] = "1";
Should we introduce a new Enum instead?

2024-06-24 13:45 UTC, andreasfrisch commented on src/SelfService/Domain/Services/AuthorizationService.cs
> +                && _httpContextAccessor.HttpContext.Items.ContainsKey("userPermissions")
Should we care about the content of the userPermission key?

2024-07-01 14:03 UTC, SEQUOIIA approved these changes

2024-07-01 14:03 UTC, merged