Send topdesk ticket for longpending deletions
dfds/selfservice-api pull request #38
Opened 2023-08-16 07:32 UTC by andreasfrisch

closes dfds/cloudplatform/issues/1870

# Question
This is technically enough, but it would be worthwhile knowing who requested the deletion in the first place.
I originally meant to create a table for managing state history like this, but was told not to spend time on this.
Question now is, do we want to extend our `Capability` table with a column for `ModifiedBy` as well?

It is not a hard thing to add, but it may not be the right solution.
On the other hand; It might be a fine solution whilst awaiting the real ownership and state management 🤷 

# Additional Review Notes
This (should) solve the ticket, but it feels half-baked. See above question.

2023-08-21 07:20 UTC, kralle333 requested changes
Looks good overall! I have some smaller comments that I would like you to look at.

2023-08-21 07:20 UTC, kralle333 commented on src/SelfService.Tests/Comparers/CapabilityComparer.cs
>      public int GetHashCode(Capability obj)
Please add Id, CreatedBy and ModifiedBy here if missing :)

2023-08-21 07:20 UTC, kralle333 commented on src/SelfService.Tests/TestDoubles/StubCapabilityRepository.cs
> +    }
Is this used in the test or does it need to be implemented because of an interface?

2023-08-21 07:20 UTC, kralle333 commented on src/SelfService/Application/CapabilityApplicationService.cs
> +                + $"Originally Created by user=\"{capability.CreatedBy}\"";
please use a StringBuilder instead :)

2023-08-21 07:20 UTC, kralle333 commented on src/SelfService/Infrastructure/BackgroundJobs/CheckPendingCapabilityDeletions.cs
> +        await applicationService.CheckPendingCapabilityDeletions();
Is it only checking capabilities that need to be deleted or does it actually delete pending capabilities. If so, please rename the function.

2023-08-21 07:20 UTC, kralle333 commented on src/SelfService/Application/CapabilityApplicationService.cs
> +
Can you add logging here, it would be nice to see in the logs that the service is running and working.

2023-08-21 11:56 UTC, andreasfrisch commented on src/SelfService.Tests/Builders/CapabilityBuilder.cs
> +        c.SetModifiedDate(_modifiedAt);
The reason I cannot, is that the Builder actually uses the real constructor -- and the real constructor does not allow for setting status and modification date specifically. I kinda like that logic, but it makes writing the tests a bit more frustrating

2023-08-21 14:14 UTC, kralle333 commented on src/SelfService.Tests/Builders/CapabilityBuilder.cs
> +        c.SetModifiedDate(_modifiedAt);
ah I see

2023-08-22 08:06 UTC, andreasfrisch commented on src/SelfService.Tests/Comparers/CapabilityComparer.cs
> +            && x.ModifiedBy == y.ModifiedBy;
Reconsidered this; I do not trust the testing framework to not need these specialised comparers.
I reintroduced them and updated them accordingly.

2023-08-22 08:54 UTC, kralle333 approved these changes
We had a short discussion about the remaining conversations and reached agreement on these.

2023-08-22 09:02 UTC, merged