Fix/1933 allow multiple topdesk ticket types
dfds/selfservice-api pull request #44
Opened 2023-08-23 13:40 UTC by andreasfrisch

closes dfds/cloudplatform/issues/1933

# Additional Review Notes
 Created a new ticket type and updated our Fake Confluent Gateway.
 
 The current Fake Confluent Gateway caused a bug, as it assumed the existence of only one Topdesk Ticket ever being present in the system. Thus it chose to add additional functionality to certain calls.
 This call to /sendnotification does not even belong to the Fake Confluent Gateway, but I have left that cleanup for later. We have to revisit our fakes anyway.
 
 This bug is not present in production, as the issue is the way we mock things locally.

2023-08-23 13:56 UTC, kralle333 requested changes

2023-08-23 13:56 UTC, kralle333 commented on src/SelfService/Domain/Models/TopdeskTicketTypes.cs
> +    protected TopdeskTicketType(string type)
Shouldnt this be private?

2023-08-23 13:56 UTC, kralle333 commented on src/SelfService/Domain/Models/TopdeskTicketTypes.cs
> +    public static readonly TopdeskTicketType capabilityDeletionRequest = new("CAPABILITY_DELETION_REQUEST");
PascalCasing :)

2023-08-23 14:21 UTC, andreasfrisch commented on src/SelfService/Domain/Models/TopdeskTicketTypes.cs
> +        Type = type;
the method is `private`, the inner variable renamed to `_value`, but the parameter is still called `type`.

I am not feeling too strongly about the `_value`-naming for inner variables, so I am okay to agree to doing this for all our enum types.

2023-08-24 07:38 UTC, kralle333 requested changes
just one last thing :) I have added a suggestion that you should be able to just apply

2023-08-24 07:38 UTC, kralle333 commented on src/SelfService/Domain/Models/TopdeskTicketTypes.cs
> +    public string _value { get; private set; }
```suggestion
    private readonly string _value;
```

2023-08-24 08:16 UTC, kralle333 approved these changes
Amazing!

2023-08-24 08:18 UTC, merged